CREATE TABLE tenant_accounts(id varchar(80) PRIMARY KEY,name varchar(200) NOT NULL);
CREATE TABLE api_credentials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id varchar(80) NOT NULL REFERENCES tenant_accounts(id),key_hash varchar(255) NOT NULL,active boolean NOT NULL);
